name: "Triploit C++ String Library"
description: "A C++ library for extended string classes."
version: "0.0.1"

authors:
    - survari
        
products:
    - ./tstring.hpp: "/usr/include/triploit/tstring.hpp"
